services:
  postgres:
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: polygate
      POSTGRES_USER: polygate
      POSTGRES_PASSWORD: polygate
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
