services:
  mongodb:
    image: mongo:8
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: elasticsearch:9
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  mongo_data:
  es_data:
