coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080

# Single-node setup
query.max-memory=4GB
query.max-memory-per-node=4GB
query.max-total-memory-per-node=6GB

# Performance
task.concurrency=4
task.max-worker-threads=8
